// This file is auto-generated by Payload CMS.
// Do not edit this file manually.
// Run `npm run generate:types` to regenerate.
import type { ImportMap } from 'payload'

export const importMap: ImportMap = {}
